language: node_js
node_js: '6.10'
deploy:
  provider: lambda
  runtime: nodejs6.1
  function_name: NcfscSkill
  role: arn:aws:iam::503962799038:role/service-role/lambda_basic_execution
  handler_name: handler
  access_key_id: AKIAJO6KJXMRMM3QEIOQ
  secret_access_key:
    secure: BFhjJiyXCRcPWiECR8XX5zlbetDywLSP+OGfSnxcZd+xrTgKw2Mw9jB3jmaf1872ufGHqkwcRSImZN2ptXO1VIeyUWihkJAvTkDrFB+OuGCByaPi08uikawsFTfRoYm9IjZajafhVrAeNZ5ZtUoinHzcrdkewNboYVVa4aaEK9TZNricGWcOBtPAowZfl34YpsJJWWu33NJXFirjRyq+KHKV0anCN4qoZksSWNbZdla/2zfmemR3eaCfnpJb3LhZo3fn82qii7VawVJGkxaMoJQTUGzQjAi0/QlKNT0TZYCjSOwJgg9f8hJDqbsuqaFAVQNEVNQJm6DWQKj558JrPI30O0++DaBQwt9HXhepa4fwlfQrGeif5TrsK0NUe20Nfd5XsLtwe5b/hIiLlHHpR5pq5wFY6420Sd7Jbpnlitjlwf/KNcxCelAWoLiEO1mjVmVD3qD9R4igNf4/9/HHgV3qRrP7AWXAgw0FOocc2UUYjjjLUFSe7ZZIGeI/eGTJfXKHvV2Nyo0VBeeVhgTmjomj5BlqkfFBhlMaDbq+KB5UghlR8pQFcS9Q129Mw2ptbsaxoWY/zA42UeEh4EamwYE2O9PpvLGNxpKtDNCk6M6WJT35KNAxmjmXNavvzEVXmox2crdjUHkYX2fydDrJf9k6CaF7gklc9JeUToUwgkU=
  on:
    branch: release